= Maven Downloader

A simple library to download Maven dependencies.


[source,xml]
----
<dependency>
    <groupId>com.javax0.mavenDownload</groupId>
    <artifactId>mavenDownloader</artifactId>
    <version>1.0.1-SNAPSHOT</version>
</dependency>
----

When you download a JAR from a Maven repository you also have to download the dependencies.
To do that programmatically you can use Maven as a library, use some wrapper around it, or you can use this library.

This library implements a limited POM parsing needed to discover dependencies and to download them programmatically.




[source,java]
----
 1
 2    private static final int NUMER_OF_FILES_IN_JAMAL_ALL_1_12_5 = 169;
 3
 4    @DisplayName("Download Jamal 1.12.5 and check that all files are downloaded")
 5    @Test
 6    void testDownload() throws Exception {
 7        final var HOME = System.getProperty("user.home");
 8        final var downloader = new Downloader(
 9                Paths.get(HOME + "/.m2/repository"),
10                Repo.MAVEN_CENTRAL);
11        downloader.exclude("com.javax0.jamal:jamal-api:*");
12        final var files = downloader.fetch("com.javax0.jamal:jamal-all:1.12.5");
13        Assertions.assertEquals(NUMER_OF_FILES_IN_JAMAL_ALL_1_12_5-1, files.length);
14        Arrays.sort(files);
15        for (final var file : files) {
16            Assertions.assertTrue(file.exists());
17        }
18    }

----

To download a Maven artifact along with the dependencies you need a `Downloader` object.
A `Downloader` needs

* a `Path` to a local repository directory where to save the downloaded files.

* One or more repositories from where to look for the artifacts.

The local repo path is the first argument.
The other arguments are one or more repos.
There are predefined repositories configured in the library.
You can use them as in the example above.
They are:

    * `MAVEN_CENTRAL` to `https://repo.maven.apache.org/maven2/`

    * `JCENTER_BINTRAY` to `https://jcenter.bintray.com/`

    * `GOOGLE_ANDROID` to `https://dl.google.com/dl/android/maven2/`

    * `GOOGLE_MAVEN_CENTRAL_AMERICAS` to `https://maven-central.storage-download.googleapis.com/repos/central/data/`

    * `GOOGLE_MAVEN_CENTRAL_EUROPE` to `https://maven-central-eu.storage-download.googleapis.com/repos/central/data/`

    * `GOOGLE_MAVEN_CENTRAL_ASIA` to `https://maven-central-asia.storage-download.googleapis.com/repos/central/data/`



You can create your own specific repository references calling

[source,java]
----
     new Repo(name, url)
----


[NOTE]
====
If you look at the code of the library in the class `Repo.class` you can see that the predefined constants are also defined this way. For example:

[source,java]
----
    final public static Repo MAVEN_CENTRAL = new Repo("central", "https://repo.maven.apache.org/maven2/");

----

assigns the repo with the name "central" to the variable `MAVEN_CENTRAL` with the well known URL of the central repo.
You can specify as many repositories as you like as the last vararg argument to the constructor of the class `Downloader`.
====

Using the `Downloader` you can call `fetch()` to download the JAR files(s).
The simplest way to call `fetch()` is to specify the dependency as a string.
This string has the format `fetch("groupId:artifactId:version")`.
The return value is an array of `java.io.File` objects pointing to the downloaded files.

You can exclude dependencies from the download calling `exclude()` on the `Downloader` object.
When you exclude a dependency it is transitive.
However, if two artifacts _A_ and _B_ both depend on _C_ and you exclude _B_, but not _A_ then _C_ will not be excluded.
Excluding a dependency simply means that the dependency will not be downloaded and parsed for further dependencies.
Exclude strings can contain ``\*`` in the place of the version or the artifactId.
GroupIds cannot contain ``*`` and are always exact matches.
Partial matches are not supported.
You cannot exclude version ```1.0.*``` for example.
